// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SxAO_yZxC_zI9uGUhDAWQvpbFCdnNBs',
    appId: '1:66205940877:web:bbceef2c9c08a62d7676c4',
    messagingSenderId: '66205940877',
    projectId: 'academic-vault-3ecde',
    authDomain: 'academic-vault-3ecde.firebaseapp.com',
    storageBucket: 'academic-vault-3ecde.firebasestorage.app',
    measurementId: 'G-X0GR1E1QV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXSpb2GFmqJcanP6v3rS70Hw5qbN8CSQ',
    appId: '1:66205940877:android:336fbf10c0550a5b7676c4',
    messagingSenderId: '66205940877',
    projectId: 'academic-vault-3ecde',
    storageBucket: 'academic-vault-3ecde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhTKOkbNKNCYb4qKp9fn6z1vflT6oPh4',
    appId: '1:66205940877:ios:fc03accfb24d26647676c4',
    messagingSenderId: '66205940877',
    projectId: 'academic-vault-3ecde',
    storageBucket: 'academic-vault-3ecde.firebasestorage.app',
    iosBundleId: 'com.example.firstAttemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkhTKOkbNKNCYb4qKp9fn6z1vflT6oPh4',
    appId: '1:66205940877:ios:fc03accfb24d26647676c4',
    messagingSenderId: '66205940877',
    projectId: 'academic-vault-3ecde',
    storageBucket: 'academic-vault-3ecde.firebasestorage.app',
    iosBundleId: 'com.example.firstAttemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SxAO_yZxC_zI9uGUhDAWQvpbFCdnNBs',
    appId: '1:66205940877:web:dd4e34f156609ccf7676c4',
    messagingSenderId: '66205940877',
    projectId: 'academic-vault-3ecde',
    authDomain: 'academic-vault-3ecde.firebaseapp.com',
    storageBucket: 'academic-vault-3ecde.firebasestorage.app',
    measurementId: 'G-28SLD17N48',
  );
}
